package com.bdc.los;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.concurrent.TimeUnit;
import java.util.Date;
import java.math.BigDecimal;
import java.math.RoundingMode;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class Applicant implements java.io.Serializable {

	static final long serialVersionUID = 1L;

	private int age;
	private Double ageAtMaturity;
	private String businessVerification;
	private String dateOFBirth;
	private String hiringDate;
	private String homeVerification;
	private Double monthlyNetIncome;
	private String name;

	private String nationalIDIssuanceDate;

	private String iscoreDate;
	private SimpleDateFormat format = new SimpleDateFormat("dd/MM/yyyy");

	private int iscoreDays;

	private int nationalIDIssuanceYears;

	private java.lang.String externalVerification;

	private java.lang.String investigationDate;

	private int investigationDays;

	private java.lang.String verificationType;

	private double yearsOfHiring;

	public Applicant() {
	}

	public int getAge() {
		this.age = this.getYearsInIntFormate(this.dateOFBirth);
		return this.age;
	}

	public void setAge(int age) {
		this.age = age;
	}

	public java.lang.Double getAgeAtMaturity() {
		return this.ageAtMaturity;
	}

	public void setAgeAtMaturity(java.lang.Double ageAtMaturity) {
		this.ageAtMaturity = ageAtMaturity;
	}

	public java.lang.String getBusinessVerification() {
		return this.businessVerification;
	}

	public void setBusinessVerification(java.lang.String businessVerification) {
		this.businessVerification = businessVerification;
	}

	public String getDateOFBirth() {
		return this.dateOFBirth;
	}

	public void setDateOFBirth(String dateOFBirth) {
		this.dateOFBirth = dateOFBirth;
	}

	public java.lang.String getHiringDate() {
		return this.hiringDate;
	}

	public void setHiringDate(java.lang.String hiringDate) {
		this.hiringDate = hiringDate;
	}

	public java.lang.String getHomeVerification() {
		return this.homeVerification;
	}

	public void setHomeVerification(java.lang.String homeVerification) {
		this.homeVerification = homeVerification;
	}

	public java.lang.Double getMonthlyNetIncome() {
		return this.monthlyNetIncome;
	}

	public void setMonthlyNetIncome(java.lang.Double monthlyNetIncome) {
		this.monthlyNetIncome = monthlyNetIncome;
	}

	public java.lang.String getName() {
		return this.name;
	}

	public void setName(java.lang.String name) {
		this.name = name;
	}

	public int getDays(String date) {
		try {
			Date startDate = format.parse(date);
			String curentDate = format.format(new Date());
			Date endDate = format.parse(curentDate);
			long difference_In_Time = endDate.getTime() - startDate.getTime();
			return (int) (TimeUnit.MILLISECONDS.toDays(difference_In_Time));
		} catch (Exception e) {
			e.printStackTrace();
			return -1;
		}
	}

	public int getMonths(String date) {
		try {
			Date startDate = format.parse(date);
			String curentDate = format.format(new Date());
			Date endDate = format.parse(curentDate);
			long difference_In_Time = endDate.getTime() - startDate.getTime();
			return (int) (TimeUnit.MILLISECONDS.toDays(difference_In_Time) % 12);
		} catch (Exception e) {
			e.printStackTrace();
			return -1;
		}
	}

	public int getYearsInIntFormate(String date) {
		try {
			Date startDate = format.parse(date);
			String curentDate = format.format(new Date());
			Date endDate = format.parse(curentDate);
			long difference_In_Time = endDate.getTime() - startDate.getTime();
			long difference_In_Years = TimeUnit.MILLISECONDS
					.toDays(difference_In_Time) / 365;
			return (int) difference_In_Years;
		} catch (Exception e) {
			e.printStackTrace();
			return -1;
		}
	}

	public double getYearsInDoubleFormate(String date) {
		try {
			Date startDate = format.parse(date);
			String curentDate = format.format(new Date());
			Date endDate = format.parse(curentDate);
			long difference_In_Time = endDate.getTime() - startDate.getTime();
			long difference_In_Days = (difference_In_Time / (1000 * 60 * 60 * 24));
			double difference_In_Years = difference_In_Days / 365.0;
			BigDecimal bd = new BigDecimal(difference_In_Years).setScale(2,
					RoundingMode.HALF_UP);
			difference_In_Years = bd.doubleValue();
			return difference_In_Years;
		} catch (Exception e) {
			e.printStackTrace();
			return -1;
		}
	}

	public java.lang.String getIscoreDate() {
		return this.iscoreDate;
	}

	public void setIscoreDate(java.lang.String iscoreDate) {
		this.iscoreDate = iscoreDate;
	}

	public int getIscoreDays() {
		return this.iscoreDays = getDays(this.iscoreDate);
	}

	public void setIscoreDays(int iscoreDays) {
		this.iscoreDays = iscoreDays;
	}

	public java.lang.String getNationalIDIssuanceDate() {
		return this.nationalIDIssuanceDate;
	}

	public void setNationalIDIssuanceDate(
			java.lang.String nationalIDIssuanceDate) {
		this.nationalIDIssuanceDate = nationalIDIssuanceDate;
	}

	public int getNationalIDIssuanceYears() {
		this.nationalIDIssuanceYears = this
				.getYearsInIntFormate(this.nationalIDIssuanceDate);
		return this.nationalIDIssuanceYears;
	}

	public void setNationalIDIssuanceYears(int nationalIDIssuanceYears) {
		this.nationalIDIssuanceYears = nationalIDIssuanceYears;
	}

	public java.lang.String getExternalVerification() {
		return this.externalVerification;
	}

	public void setExternalVerification(java.lang.String externalVerification) {
		this.externalVerification = externalVerification;
	}

	public java.lang.String getInvestigationDate() {
		return this.investigationDate;
	}

	public void setInvestigationDate(java.lang.String investigationDate) {
		this.investigationDate = investigationDate;
	}

	public java.lang.Integer getInvestigationDays() {

		return this.investigationDays = getDays(this.investigationDate);

	}

	public void setInvestigationDays(java.lang.Integer investigationDays) {
		this.investigationDays = investigationDays;
	}

	public java.lang.String getVerificationType() {
		return this.verificationType;
	}

	public void setVerificationType(java.lang.String verificationType) {
		this.verificationType = verificationType;
	}

	public double getYearsOfHiring() {
		return this.yearsOfHiring = getYearsInDoubleFormate(this.hiringDate);
	}

	public void setYearsOfHiring(double yearsOfHiring) {
		this.yearsOfHiring = yearsOfHiring;
	}

	public Applicant(int age, java.lang.Double ageAtMaturity,
			java.lang.String businessVerification,
			java.lang.String dateOFBirth, java.lang.String hiringDate,
			java.lang.String homeVerification,
			java.lang.Double monthlyNetIncome, java.lang.String name,
			java.lang.String nationalIDIssuanceDate,
			java.lang.String iscoreDate, java.text.SimpleDateFormat format,
			int iscoreDays, int nationalIDIssuanceYears,
			java.lang.String externalVerification,
			java.lang.String investigationDate, int investigationDays,
			java.lang.String verificationType, double yearsOfHiring) {
		this.age = age;
		this.ageAtMaturity = ageAtMaturity;
		this.businessVerification = businessVerification;
		this.dateOFBirth = dateOFBirth;
		this.hiringDate = hiringDate;
		this.homeVerification = homeVerification;
		this.monthlyNetIncome = monthlyNetIncome;
		this.name = name;
		this.nationalIDIssuanceDate = nationalIDIssuanceDate;
		this.iscoreDate = iscoreDate;
		this.format = format;
		this.iscoreDays = iscoreDays;
		this.nationalIDIssuanceYears = nationalIDIssuanceYears;
		this.externalVerification = externalVerification;
		this.investigationDate = investigationDate;
		this.investigationDays = investigationDays;
		this.verificationType = verificationType;
		this.yearsOfHiring = yearsOfHiring;
	}

}
