package com.bdc.los;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.concurrent.TimeUnit;
import java.util.Date;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class Applicant implements java.io.Serializable {

	static final long serialVersionUID = 1L;

	private int age;
	private Double ageAtMaturity;
	private String businessVerification;
	private String dateOFBirth;
	private int daysOfHiring;
	private String hiringDate;
	private String homeVerification;
	private Double monthlyNetIncome;
	private String name;

	private String nationalIDIssuanceDate;

	private String iscoreDate;
	private SimpleDateFormat format = new SimpleDateFormat("dd/MM/yyyy");

	private int iscoreDays;

	private int nationalIDIssuanceYears;

	public Applicant() {
	}

	public int getAge() {
		this.age = this.getYears(this.dateOFBirth);
		return this.age;
	}

	public void setAge(int age) {
		this.age = age;
	}

	public java.lang.Double getAgeAtMaturity() {
		return this.ageAtMaturity;
	}

	public void setAgeAtMaturity(java.lang.Double ageAtMaturity) {
		this.ageAtMaturity = ageAtMaturity;
	}

	public java.lang.String getBusinessVerification() {
		return this.businessVerification;
	}

	public void setBusinessVerification(java.lang.String businessVerification) {
		this.businessVerification = businessVerification;
	}

	public String getDateOFBirth() {
		return this.dateOFBirth;
	}

	public void setDateOFBirth(String dateOFBirth) {
		this.dateOFBirth = dateOFBirth;
	}

	public int getDaysOfHiring() {

		return this.daysOfHiring = getYears(this.hiringDate);

	}

	public void setDaysOfHiring(int daysOfHiring) {
		this.daysOfHiring = daysOfHiring;
	}

	public java.lang.String getHiringDate() {
		return this.hiringDate;
	}

	public void setHiringDate(java.lang.String hiringDate) {
		this.hiringDate = hiringDate;
	}

	public java.lang.String getHomeVerification() {
		return this.homeVerification;
	}

	public void setHomeVerification(java.lang.String homeVerification) {
		this.homeVerification = homeVerification;
	}

	public java.lang.Double getMonthlyNetIncome() {
		return this.monthlyNetIncome;
	}

	public void setMonthlyNetIncome(java.lang.Double monthlyNetIncome) {
		this.monthlyNetIncome = monthlyNetIncome;
	}

	public java.lang.String getName() {
		return this.name;
	}

	public void setName(java.lang.String name) {
		this.name = name;
	}

	public int getDays(String date) {
		try {
			Date startDate = format.parse(date);
			String curentDate = format.format(new Date());
			Date endDate = format.parse(curentDate);
			long difference_In_Time = endDate.getTime() - startDate.getTime();
			return (int) (TimeUnit.MILLISECONDS.toDays(difference_In_Time));
		} catch (Exception e) {
			e.printStackTrace();
			return -1;
		}
	}

	public int getMonths(String date) {
		try {
			Date startDate = format.parse(date);
			String curentDate = format.format(new Date());
			Date endDate = format.parse(curentDate);
			long difference_In_Time = endDate.getTime() - startDate.getTime();
			return (int) (TimeUnit.MILLISECONDS.toDays(difference_In_Time) % 12);
		} catch (Exception e) {
			e.printStackTrace();
			return -1;
		}
	}

	public int getYears(String date) {
		try {
			Date startDate = format.parse(date);
			String curentDate = format.format(new Date());
			Date endDate = format.parse(curentDate);
			long difference_In_Time = endDate.getTime() - startDate.getTime();
			long difference_In_Years = TimeUnit.MILLISECONDS
					.toDays(difference_In_Time) / 365;
			return (int) difference_In_Years;
		} catch (Exception e) {
			e.printStackTrace();
			return -1;
		}
	}

	public java.lang.String getIscoreDate() {
		return this.iscoreDate;
	}

	public void setIscoreDate(java.lang.String iscoreDate) {
		this.iscoreDate = iscoreDate;
	}

	public int getIscoreDays() {
		return this.iscoreDays = getDays(this.iscoreDate);
	}

	public void setIscoreDays(int iscoreDays) {
		this.iscoreDays = iscoreDays;
	}

	public java.lang.String getNationalIDIssuanceDate() {
		return this.nationalIDIssuanceDate;
	}

	public void setNationalIDIssuanceDate(
			java.lang.String nationalIDIssuanceDate) {
		this.nationalIDIssuanceDate = nationalIDIssuanceDate;
	}

	public int getNationalIDIssuanceYears() {
		this.nationalIDIssuanceYears = this
				.getYears(this.nationalIDIssuanceDate);
		return this.nationalIDIssuanceYears;
	}

	public void setNationalIDIssuanceYears(int nationalIDIssuanceYears) {
		this.nationalIDIssuanceYears = nationalIDIssuanceYears;
	}

	public Applicant(int age, java.lang.Double ageAtMaturity,
			java.lang.String businessVerification,
			java.lang.String dateOFBirth, int daysOfHiring,
			java.lang.String hiringDate, java.lang.String homeVerification,
			java.lang.Double monthlyNetIncome, java.lang.String name,
			java.lang.String nationalIDIssuanceDate,
			java.lang.String iscoreDate, java.text.SimpleDateFormat format,
			int iscoreDays, int nationalIDIssuanceYears) {
		this.age = age;
		this.ageAtMaturity = ageAtMaturity;
		this.businessVerification = businessVerification;
		this.dateOFBirth = dateOFBirth;
		this.daysOfHiring = daysOfHiring;
		this.hiringDate = hiringDate;
		this.homeVerification = homeVerification;
		this.monthlyNetIncome = monthlyNetIncome;
		this.name = name;
		this.nationalIDIssuanceDate = nationalIDIssuanceDate;
		this.iscoreDate = iscoreDate;
		this.format = format;
		this.iscoreDays = iscoreDays;
		this.nationalIDIssuanceYears = nationalIDIssuanceYears;
	}

}