package com.bdc.los;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.concurrent.TimeUnit;
import java.util.Date;
import java.math.BigInteger;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class Loan implements java.io.Serializable {

	static final long serialVersionUID = 1L;

	private java.lang.String productCode;

	private Long financeAmount;

	private java.lang.Double tenor;
	private java.lang.Double totalDBR;

	private java.lang.Double interestRate;

	private java.lang.String investigationDate;

	private java.lang.Double maximumInstallment;

	private java.lang.Double installment;

	private java.lang.String incomeType;

	private java.lang.String deviationOne;
	private java.lang.String deviationTwo;
	private java.lang.String deviationThree;

	private java.lang.Boolean dateOfBirthApprove = false;
	private Boolean hiringDateApprove = false;
	private java.lang.Boolean monthlyNetInComeApprove = false;
	private java.lang.Boolean homeVerificationApprove = false;
	private java.lang.Boolean businessVerificationApprove = false;
	private java.lang.Boolean financeAmountApprove = false;
	private java.lang.Boolean tenorApprove = false;
	private java.lang.Boolean totalDBRApprove = false;
	private java.lang.Boolean customerAgeAtMaturityApprove = false;
	private java.lang.Boolean nationalIDIssuanceDateApprove = false;
	private java.lang.Boolean loanApprove = false;
	private java.lang.Boolean iscoreDateApprove = false;
	private java.lang.Boolean investigationDateApprove = false;
	private java.lang.Boolean installmentApprove = false;

	private java.lang.Integer minFinanceAmount;
	private SimpleDateFormat format = new SimpleDateFormat("dd/MM/yyyy");

	private java.lang.Integer investigationDays;

	private java.lang.String auditorsNames;

	public Loan() {
	}

	public java.lang.String getProductCode() {
		return this.productCode;
	}

	public void setProductCode(java.lang.String productCode) {
		this.productCode = productCode;
	}

	public java.lang.Double getTenor() {
		return this.tenor;
	}

	public void setTenor(java.lang.Double tenor) {
		this.tenor = tenor;
	}

	public java.lang.Double getTotalDBR() {
		return this.totalDBR;
	}

	public void setTotalDBR(java.lang.Double totalDBR) {
		this.totalDBR = totalDBR;
	}

	public java.lang.String getdeviationOne() {
		return this.deviationOne;
	}

	public void setdeviationOne(java.lang.String deviationOne) {
		this.deviationOne = deviationOne;
	}

	public java.lang.String getDeviationTwo() {
		return this.deviationTwo;
	}

	public void setDeviationTwo(java.lang.String deviationTwo) {
		this.deviationTwo = deviationTwo;
	}

	public java.lang.String getDeviationThree() {
		return this.deviationThree;
	}

	public void setDeviationThree(java.lang.String deviationThree) {
		this.deviationThree = deviationThree;
	}

	public java.lang.Boolean getDateOfBirthApprove() {
		return this.dateOfBirthApprove;
	}

	public void setDateOfBirthApprove(java.lang.Boolean dateOfBirthApprove) {
		this.dateOfBirthApprove = dateOfBirthApprove;
	}

	public java.lang.Boolean getHiringDateApprove() {
		return this.hiringDateApprove;
	}

	public void setHiringDateApprove(java.lang.Boolean hiringDateApprove) {
		this.hiringDateApprove = hiringDateApprove;
	}

	public java.lang.Boolean getMonthlyNetInComeApprove() {
		return this.monthlyNetInComeApprove;
	}

	public void setMonthlyNetInComeApprove(
			java.lang.Boolean monthlyNetInComeApprove) {
		this.monthlyNetInComeApprove = monthlyNetInComeApprove;
	}

	public java.lang.Boolean getHomeVerificationApprove() {
		return this.homeVerificationApprove;
	}

	public void setHomeVerificationApprove(
			java.lang.Boolean homeVerificationApprove) {
		this.homeVerificationApprove = homeVerificationApprove;
	}

	public java.lang.Boolean getBusinessVerificationApprove() {
		return this.businessVerificationApprove;
	}

	public void setBusinessVerificationApprove(
			java.lang.Boolean businessVerificationApprove) {
		this.businessVerificationApprove = businessVerificationApprove;
	}

	public java.lang.Boolean getFinanceAmountApprove() {
		return this.financeAmountApprove;
	}

	public void setFinanceAmountApprove(java.lang.Boolean financeAmountApprove) {
		this.financeAmountApprove = financeAmountApprove;
	}

	public void setTenorApprove(java.lang.Boolean tenorApprove) {
		this.tenorApprove = tenorApprove;
	}

	public java.lang.Boolean getTenorApprove() {
		return this.tenorApprove;

	}

	public java.lang.Boolean getTotalDBRApprove() {
		return this.totalDBRApprove;
	}

	public void setTotalDBRApprove(java.lang.Boolean totalDBRApprove) {
		this.totalDBRApprove = totalDBRApprove;
	}

	public java.lang.Boolean getCustomerAgeAtMaturityApprove() {
		return this.customerAgeAtMaturityApprove;
	}

	public void setCustomerAgeAtMaturityApprove(
			java.lang.Boolean customerAgeAtMaturityApprove) {
		this.customerAgeAtMaturityApprove = customerAgeAtMaturityApprove;
	}

	public java.lang.Boolean getNationalIDIssuanceDateApprove() {
		return this.nationalIDIssuanceDateApprove;
	}

	public void setNationalIDIssuanceDateApprove(
			java.lang.Boolean nationalIDIssuanceDateApprove) {
		this.nationalIDIssuanceDateApprove = nationalIDIssuanceDateApprove;
	}

	public java.lang.Double getInterestRate() {
		return this.interestRate;
	}

	public void setInterestRate(java.lang.Double interestRate) {
		this.interestRate = interestRate;
	}

	public java.lang.Boolean getLoanApprove() {
		return this.loanApprove;
	}

	public void setLoanApprove(java.lang.Boolean loanApprove) {
		this.loanApprove = loanApprove;
	}

	public java.lang.Boolean getIscoreDateApprove() {
		return this.iscoreDateApprove;
	}

	public void setIscoreDateApprove(java.lang.Boolean iscoreDateApprove) {
		this.iscoreDateApprove = iscoreDateApprove;
	}

	public java.lang.Boolean getInvestigationDateApprove() {
		return this.investigationDateApprove;
	}

	public void setInvestigationDateApprove(
			java.lang.Boolean investigationDateApprove) {
		this.investigationDateApprove = investigationDateApprove;
	}

	public java.lang.String getInvestigationDate() {
		return this.investigationDate;
	}

	public void setInvestigationDate(java.lang.String investigationDate) {
		this.investigationDate = investigationDate;
	}

	public java.lang.Double getMaximumInstallment() {
		return this.maximumInstallment;
	}

	public void setMaximumInstallment(java.lang.Double maximumInstallment) {
		this.maximumInstallment = maximumInstallment;
	}

	public java.lang.Double getInstallment() {
		return this.installment;
	}

	public void setInstallment(java.lang.Double installment) {
		this.installment = installment;
	}

	public java.lang.String getIncomeType() {
		return this.incomeType;
	}

	public void setIncomeType(java.lang.String incomeType) {
		this.incomeType = incomeType;
	}

	public java.lang.Boolean getInstallmentApprove() {
		return this.installmentApprove;
	}

	public void setInstallmentApprove(java.lang.Boolean installmentApprove) {
		this.installmentApprove = installmentApprove;
	}

	public java.lang.Integer getMinFinanceAmount() {
		return this.minFinanceAmount;
	}

	public void setMinFinanceAmount(java.lang.Integer minFinanceAmount) {
		this.minFinanceAmount = minFinanceAmount;
	}

	public int getDays(String date) {
		try {
			Date startDate = format.parse(date);
			String curentDate = format.format(new Date());
			Date endDate = format.parse(curentDate);
			long difference_In_Time = endDate.getTime() - startDate.getTime();
			return (int) (TimeUnit.MILLISECONDS.toDays(difference_In_Time));
		} catch (Exception e) {
			e.printStackTrace();
			return -1;
		}
	}

	public int getMonths(String date) {
		try {
			Date startDate = format.parse(date);
			String curentDate = format.format(new Date());
			Date endDate = format.parse(curentDate);
			long difference_In_Time = endDate.getTime() - startDate.getTime();
			return (int) (TimeUnit.MILLISECONDS.toDays(difference_In_Time) % 12);
		} catch (Exception e) {
			e.printStackTrace();
			return -1;
		}
	}

	public int getYears(String date) {
		try {
			Date startDate = format.parse(date);
			String curentDate = format.format(new Date());
			Date endDate = format.parse(curentDate);
			long difference_In_Time = endDate.getTime() - startDate.getTime();
			long difference_In_Years = TimeUnit.MILLISECONDS
					.toDays(difference_In_Time) / 365;
			return (int) difference_In_Years;
		} catch (Exception e) {
			e.printStackTrace();
			return -1;
		}
	}

	public java.lang.Integer getInvestigationDays() {

		return this.investigationDays = getDays(this.investigationDate);

	}

	public void setInvestigationDays(java.lang.Integer investigationDays) {
		this.investigationDays = investigationDays;
	}

	public java.lang.String getAuditorsNames() {
		return this.auditorsNames;
	}

	public void setAuditorsNames(java.lang.String auditorsNames) {
		this.auditorsNames = auditorsNames;
	}

	public java.lang.Long getFinanceAmount() {
		return this.financeAmount;
	}

	public void setFinanceAmount(java.lang.Long financeAmount) {
		this.financeAmount = financeAmount;
	}

	public Loan(java.lang.String productCode, java.lang.Long financeAmount,
			java.lang.Double tenor, java.lang.Double totalDBR,
			java.lang.Double interestRate, java.lang.String investigationDate,
			java.lang.Double maximumInstallment, java.lang.Double installment,
			java.lang.String incomeType, java.lang.String deviationOne,
			java.lang.String deviationTwo, java.lang.String deviationThree,
			java.lang.Boolean dateOfBirthApprove,
			java.lang.Boolean hiringDateApprove,
			java.lang.Boolean monthlyNetInComeApprove,
			java.lang.Boolean homeVerificationApprove,
			java.lang.Boolean businessVerificationApprove,
			java.lang.Boolean financeAmountApprove,
			java.lang.Boolean tenorApprove, java.lang.Boolean totalDBRApprove,
			java.lang.Boolean customerAgeAtMaturityApprove,
			java.lang.Boolean nationalIDIssuanceDateApprove,
			java.lang.Boolean loanApprove, java.lang.Boolean iscoreDateApprove,
			java.lang.Boolean investigationDateApprove,
			java.lang.Boolean installmentApprove,
			java.lang.Integer minFinanceAmount,
			java.text.SimpleDateFormat format,
			java.lang.Integer investigationDays, java.lang.String auditorsNames) {
		this.productCode = productCode;
		this.financeAmount = financeAmount;
		this.tenor = tenor;
		this.totalDBR = totalDBR;
		this.interestRate = interestRate;
		this.investigationDate = investigationDate;
		this.maximumInstallment = maximumInstallment;
		this.installment = installment;
		this.incomeType = incomeType;
		this.deviationOne = deviationOne;
		this.deviationTwo = deviationTwo;
		this.deviationThree = deviationThree;
		this.dateOfBirthApprove = dateOfBirthApprove;
		this.hiringDateApprove = hiringDateApprove;
		this.monthlyNetInComeApprove = monthlyNetInComeApprove;
		this.homeVerificationApprove = homeVerificationApprove;
		this.businessVerificationApprove = businessVerificationApprove;
		this.financeAmountApprove = financeAmountApprove;
		this.tenorApprove = tenorApprove;
		this.totalDBRApprove = totalDBRApprove;
		this.customerAgeAtMaturityApprove = customerAgeAtMaturityApprove;
		this.nationalIDIssuanceDateApprove = nationalIDIssuanceDateApprove;
		this.loanApprove = loanApprove;
		this.iscoreDateApprove = iscoreDateApprove;
		this.investigationDateApprove = investigationDateApprove;
		this.installmentApprove = installmentApprove;
		this.minFinanceAmount = minFinanceAmount;
		this.format = format;
		this.investigationDays = investigationDays;
		this.auditorsNames = auditorsNames;
	}

}