package com.bdc.los;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class SecuredLoan implements java.io.Serializable {

	static final long serialVersionUID = 1L;

	private java.lang.String productCode;
	private double requestedAmount;
	private double pledgedAmount;
	private String tDCode;
	private boolean securedloansApprove = false;

	private double availableAmount;

	private java.lang.String rejectionReason;

	public SecuredLoan() {
	}

	public java.lang.String getProductCode() {
		return this.productCode;
	}

	public void setProductCode(java.lang.String productCode) {
		this.productCode = productCode;
	}

	public boolean isSecuredloansApprove() {
		return this.securedloansApprove;
	}

	public void setSecuredloansApprove(boolean securedloansApprove) {
		this.securedloansApprove = securedloansApprove;
	}

	public double getRequestedAmount() {
		return this.requestedAmount;
	}

	public void setRequestedAmount(double requestedAmount) {
		this.requestedAmount = requestedAmount;
	}

	public double getPledgedAmount() {
		return this.pledgedAmount;
	}

	public void setPledgedAmount(double pledgedAmount) {
		this.pledgedAmount = pledgedAmount;
	}

	public java.lang.String gettDCode() {
		return this.tDCode;
	}

	public void settDCode(java.lang.String tDCode) {
		this.tDCode = tDCode;
	}

	public double getAvailableAmount() {
		return this.availableAmount;
	}

	public void setAvailableAmount(double availableAmount) {
		this.availableAmount = availableAmount;
	}

	public java.lang.String getRejectionReason() {
		return this.rejectionReason;
	}

	public void setRejectionReason(java.lang.String rejectionReason) {
		this.rejectionReason = rejectionReason;
	}

	public SecuredLoan(java.lang.String productCode, double requestedAmount,
			double pledgedAmount, java.lang.String tDCode,
			boolean securedloansApprove, double availableAmount,
			java.lang.String rejectionReason) {
		this.productCode = productCode;
		this.requestedAmount = requestedAmount;
		this.pledgedAmount = pledgedAmount;
		this.tDCode = tDCode;
		this.securedloansApprove = securedloansApprove;
		this.availableAmount = availableAmount;
		this.rejectionReason = rejectionReason;
	}

}